[package]
name = "pxp-index"
version = "0.1.0"
edition = "2021"
license-file.workspace = true
rust-version.workspace = true

[dependencies]
pxp-ast = { version = "0.1.0", path = "../pxp-ast" }
pxp-parser = { version = "0.1.0", path = "../pxp-parser" }
pxp-span = { version = "0.1.0", path = "../pxp-span" }
pxp-symbol = { version = "0.1.0", path = "../pxp-symbol" }
pxp-type = { version = "0.1.0", path = "../pxp-type" }
pxp-visitor = { version = "0.1.0", path = "../pxp-visitor" }

[dev-dependencies]
discoverer = "0.2.0"
pxp-parser = { path = "../pxp-parser" }
