[package]
name = "pxp-token"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
pxp-bytestring = { path = "../bytestring" }
pxp-span = { path = "../span" }
serde = { workspace = true }
