[package]
name = "pxp-type"
version = "0.1.0"
edition = "2021"
license-file.workspace = true

[dependencies]
pxp-span = { path = "../pxp-span" }
serde = { version = "1.0.193", features = ["derive"] }
